---
title: "Research Strategy and Sample Size Estimation"
author: "Joe Nagel"
date: ""
output: 
  pdf_document:
    number_sections: false
fontsize: 12pt
mainfont: Helvetica
geometry: margin=1in
header-includes:
  - \usepackage{float}
  - \usepackage{setspace}
  - \doublespacing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```

#### Aim 1 Research Strategy
All six outcomes of interest for this aim are continuous and include AD-signature cortical thickness and five cognitive measures capturing recall/recognition (California Verbal Learning Test-II and Benson Figure), pattern separation (Mnemonic Similarity Task), and long term memory consolidation (Story Recall). We will use two cytokines (IL-6 and TNF-alpha) and two chemokines (MCP-1 and eotaxin-1) as our measures of peripheral inflammation. To investigate the relationship between the baseline measures of peripheral inflammation and the outcomes of interest (**Hypothesis 1a**), we will model the Year‑1 minus baseline change in each outcome as a function of each baseline inflammation measure, separately, and the baseline value of the outcome using regression analysis; this approach will allow us to estimate the magnitude and direction of the relationship between the outcomes and each of the inflammation measures. To determine if increases in measures of inflammation are associated with worse outcomes (**Hypothesis 1b**), we will refit the previous models using the Year-1 minus baseline change in inflammation measures in place of the baseline inflammation measures. All models fit to address **Hypotheses 1a** and **1b** will control for age and sex. We will additionally consider other measures potentially associated with inflammation: cardiovascular risk markers (BMI, blood pressure, and history of hypercholesterolemia), NSAID use, and immune-related health conditions (Crohn's disease, irritable bowel syndrome, and arthritis). For these measures, we will use exploratory analysis to investigate their relationship with the outcomes and predictors; leveraging the results, we will decide which measures to include in the final analysis.

We will perform a power analysis for both **Hypotheses 1a** and **1b** by simplifying each regression into a correlation between an inflammation measure and an outcome. We will define both expected and clinically meaningful correlations and investigate the power to detect the relationships at the current sample size of 175. We will also calculate power for additional sample sizes to establish a complete characterization of the required sample size. Because this approach does not account for the additional covariates in the analysis, in the absense of confounders, it will produce conservative estimates.

<!-- Hypothesis: -->

<!-- We will employ novel measures of both peripheral inflammation and cognition to test our hypotheses that higher baseline cytokine and chemokine levels in circulating plasma will predict declines in memory consolidation and decreases in AD-signature cortical thickness (Hypothesis 1a), and that greater increases in cytokines and chemokines will be associated with greater declines in episodic memory and cortical thickness (Hypothesis 1b). -->

<!-- 1b) how are we modeling change? -->

<!-- Outcomes: -->

<!-- * Cognitive (total 5; all continuous) -->
<!--     * Recall/Recog. -->
<!--         * CVLT (California Verbal Learning Test) -->
<!--             * Total Correct --> 
<!--             * Recog. -->
<!--         * Benson Figure -->
<!--             * figure recall -->
<!--     * Pattern Recog. -->
<!--         MST (Mnemonic Similarity Task) -->
<!--     * Long Term Consolidation -->
<!--         * Story Recall -->
<!-- * Mean cortical thickness -->

<!-- Predictors: (are we fitting models with all of the inflammation measures at once?) -->
<!-- * IL-6 (cytokine) -->
<!-- * TNF-alpha (cytokine) -->
<!-- * MCP-1 (chemokine) -->
<!-- * Eotaxin-1 (chemokine) -->

<!-- Covariates: -->
<!-- * age -->
<!-- * sex -->
<!-- * APOE genotype -->
<!-- * cardiovascular risk factors -->
<!--     * BMI -->
<!--     * blood pressure -->
<!--     * history of hypercholesterolemia -->
<!-- * NSAID use -->
<!-- * immune related health conditions -->
<!--     * Crohn's -->
<!--     * IBS -->
<!--     * arthritis -->

<!-- Analysis approach: -->
<!-- Regression of cognitive outcomes and cortical thickness on cytokines and chemokines adjusting for age, sex, confounders and health measures related to inflammation -->


#### Aim 2 Research Strategy

This Aim involves the same inflammation measures and outcomes as Aim 1 in addition to a continuous measure of amyloid deposition. To investigate the interaction between amyloid deposition and peripheral inflammation markers (**Hypothesis 2**), we will refit the models from **Hypothesis 1b** that demonstrated a significant relationship between the inflammation marker and outcome. In these models, we will add an interaction term between the change in the inflammation marker and amyloid deposition. This will allow us to determine whether declines in memory and AD‑signature cortical thickness are greatest when both amyloid deposition is high and peripheral inflammation is elevated. These models will adjust for age, sex, and any additional measures related to inflammation found through the exploratory process described in Aim 1.

Consistent with Aim 1, we will estimate power by simplifying the interaction effect of interest to an equivalent correlation. We will calculate the power to detect expected and clinically meaningful correlations across a range of sample sizes, including the current target sample of 175.

<!-- Hypothesis: -->

<!-- We will test our hypothesis of an interaction between peripheral levels of inflammation and amyloid deposition, such that the presence of both significant amyloid deposition and elevated peripheral inflammatory markers will -->
<!-- be the strongest predictors of memory decline and decline in AD-signature cortical thickness over a one year period. This stems from our hypothesis that there is an exaggerated inflammatory response that contributes to AD pathological processes and is more pronounced and pervasive than in non-AD aging. Results gleaned from this Aim will provide new insights into the relationship(s) between inflammation and underlying amyloid pathology in predicting clinical progression. -->



<!-- Outcomes: -->

<!-- * Cognitive -->
<!--     * Recall/Recog. -->
<!--         * CVLT (California Verbal Learning Test) -->
<!--             * List learning measure -->
<!--         * Benson Figure -->
<!--             * figure recall -->
<!--     * Pattern Recog. -->
<!--         MST (Mnemonic Similarity Task) -->
<!--     * Long Term Consolidation -->
<!--         * Story Recall -->
<!-- * Mean cortical thickness -->

<!-- Predictors: (are we fitting models with all of the inflammation measures at once?) -->
<!-- * IL-6 (cytokine) -->
<!-- * TNF-alpha (cytokine) -->
<!-- * MCP-1 (chemokine) -->
<!-- * Eotaxin-1 (chemokine) -->
<!-- * amyloid deposition (continuous) -->

<!-- Covariates: -->
<!-- * age -->
<!-- * sex -->
<!-- * confounders -->
<!--     * cardiovascular risk -->
<!--     * immuno. health history -->
<!--     * APOE genotype -->
<!-- * health measures -->
<!--     * BMI -->
<!--     * history of hypercholesterolemia -->
<!--     * NSAID use -->
<!--     * immune-related health conditions -->


<!-- # Power Analysis -->

<!-- 10% attrition expected over 1 year -->
<!-- Recruit (already maximum): 138 aMCI and 56 HC -->
<!-- Goal at year 1: 125 aMCI and 50 HC -->




